### ISSUE TITLE
Figure out what's going on with Jasmine 2.0

### ISSUE THREAD

**Issue by juliemr** [juliemr/minijasminenode#9]
Comments here hint that they're doing their own npm package:

https://github.com/pivotal/jasmine/pull/482

Which would be great, but I'm not sure if there's any sort of ETA at all.

**Comment by juliemr** [comment]
Trying out Jasmine 2.0 in the jasmine2 branch. Everything works _except_ for specifying a timeout specifically for a test, which there is now no way to do without modifying the Jasmine code itself.

**Comment by wyuenho** [comment]
Can you elaborate on the timeout issue?

**Comment by juliemr** [comment]
https://github.com/pivotal/jasmine/issues/483

**Comment by infews** [comment]
Hey there - we've now made our repo public, but are not yet ready to publish the NPM.

**Comment by cyrret** [comment]
We are interested in using Protractor with jasmine 2.0, which relies on this issue being resolved. We tried your jasmine2 branch and everything appears to be working regarding jasmine timeout intervals. Is there any further hold up? We are part of Pivotal and would like to help.

**Comment by cyrret** [comment]
Also, we noticed that you are not dependent on jasmine-core. We've submitted pull request #14 to address this. Thanks!

**Comment by juliemr** [comment]
Hi @cyrret - I'd be happy to work to Jasmine 2.0! On my last view, things were still settling down with Jasmine, so I was waiting for the dust to settle on 2.0 and its relationship with node. If you think it's ready now, I'd be happy to take another look. Ideally, I don't think minijasminenode should exist at all!

**Comment by cyrret** [comment]
Hi Julie - we've been working on a simple Jasmine runner for node here:
https://github.com/pivotal/jasmine-npm

Compared to minijasminenode it's missing the following:
1. Ability to set a custom reporter (vs just console output)
2. Exposure of the following options to users:
  jasmineNodeOpts: {
    // onComplete will be called just before the driver quits.
    onComplete: null,
    // If true, display spec names.
    isVerbose: false,
    // If true, print colors to the terminal.
    showColors: false,
    // If true, include stack traces in failures.
    includeStackTrace: true,
    // Default time to wait in ms before a test fails.
    defaultTimeoutInterval: 30000
  },
3. Programmatic invocation

If you can live without these in Protractor, then we encourage you to
migrate to jasmine-npm and deprecate minijasminenode.

If you need these features, then our current approach is that folks build
something like minijasminenode, but do it on top of jasmine-core vs simply
embedding a copy of jasmine within your runner. I have a pull request out
on minijasminenode that makes the pertinent changes for this.

We're open to feedback/discussing whether this overall approach is
reasonable. Thoughts?

---

Terry Chen
tchen120@gmail.com

**Comment by juliemr** [comment]
@cyrret those features are all pretty key. Are there plans to include any of them in jasmine-npm in the future? Jasmine 1.3 is working as is, so there's not a real rush to update minijasminenode for my use cases - I'd be happy to wait for these features if they're in the pipeline.

Otherwise, using jasmine-core instead of embedding a copy sounds entirely reasonable. Just curious.

EDIT - to clarify, (1) and (3) are the really important features. Setting timeouts is also important, as described in pivotal/jasmine#483

**Comment by juliemr** [comment]
Done in 889a53c76a4211f7a68fd4b89b25fd0979a35f3e
